"""include website

Revision ID: 1f39f34d358d
Revises: 27d753f52808
Create Date: 2021-03-08 17:17:32.655277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f39f34d358d'
down_revision = '27d753f52808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    op.add_column('Venue', sa.Column('seeking', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking')
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking')
    # ### end Alembic commands ###
